FROM node:18-alpine

ENV NODE_ENV production
ENV NPM_CONFIG_LOGLEVEL warn

RUN mkdir /home/node/app/ && chown -R node:node /home/node/app

WORKDIR /home/node/app

COPY ./app/package.json ./
COPY ./app/yarn.lock ./

USER node

RUN yarn install --production
RUN yarn build

COPY --chown=node:node ./app/.next .next
COPY --chown=node:node ./app/public public

EXPOSE 3000


CMD yarn start